### PR TITLE
Added Winning Score input field and changed app.js accordingly

### PR DESCRIPTION
**Pull request by shaurya5**

### CODE REVIEW

**Comment by shaurya5** [comment]
Also updated the reset function in the latest commit

**Comment by ANIK-DATTA** [comment]
There is some bug with the reset button
After clicking the reset button scores are not updated back to 0 but saving the previous round scores and continuing and also disabled all the buttons until the round is not set with the set button.
Please fix it.

**Comment by shaurya5** [comment]
@ANIK-DATTA I fixed that too

**Comment by shaurya5** [comment]
@ANIK-DATTA also please merge this pull request

**Comment by shaurya5** [comment]
resolved the conflicts

**Comment by shaurya5** [comment]
please merge this PR if it's alright

**Comment by shaurya5** [comment]
@ANIK-DATTA you didn't add the hacktoberfest label.. can you add it please?

**Comment by ANIK-DATTA** [comment]
Don't worry it will be accepted automatically

**Pull request merged**
